In [1]:
import numpy as np 


In [2]:
np.__version__

'2.4.3'

# Create & Read 

In [3]:
# 1D array
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [4]:
type(arr)

numpy.ndarray

In [6]:
arr.shape

(5,)

In [7]:
arr.dtype

dtype('int64')

In [8]:
 arr.ndim

1

In [9]:
arr.size

5

In [5]:
# 2d araay
arr2 = np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
arr2.shape

(2, 3)

In [6]:
# 3d array
arr3 = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
arr3

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [17]:
arr3.ndim


3

In [18]:
arr3.shape

(2, 2, 3)

In [7]:
# random array
random = np.random.rand(3,2,3)
random

array([[[0.54281653, 0.33450452, 0.87009875],
        [0.42179336, 0.83054817, 0.966609  ]],

       [[0.6538606 , 0.10454578, 0.63833409],
        [0.45162171, 0.71370034, 0.5608089 ]],

       [[0.75306199, 0.74825554, 0.58741394],
        [0.71432253, 0.89299001, 0.10095909]]])

In [8]:
zeros = np.zeros((3,2,3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [9]:
full = np.full((3,2,3),8)
full

array([[[8, 8, 8],
        [8, 8, 8]],

       [[8, 8, 8],
        [8, 8, 8]],

       [[8, 8, 8],
        [8, 8, 8]]])

In [10]:
ones = np.ones((3,2,3))
ones

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [27]:
arr3

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [28]:
arr3[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
arr3[0][0]

np.int64(1)

In [31]:
arr3[0][0][0]

np.int64(1)

In [38]:
arr3[0:1]

array([[[1, 2, 3],
        [4, 5, 6]]])

In [39]:
arr3[-1]

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
arr3[1,0,1]

np.int64(2)

# update and delete values 

In [11]:
a1 = np.random.rand(2,3,2)
a2 = np.random.rand(2,3,2)

In [12]:
a1

array([[[0.42566049, 0.23680083],
        [0.86429505, 0.62432737],
        [0.91962224, 0.99294472]],

       [[0.24942827, 0.29991547],
        [0.07213856, 0.3293924 ],
        [0.98795915, 0.21784378]]])

In [13]:
a2

array([[[0.63526014, 0.32517498],
        [0.40405078, 0.49435711],
        [0.34689608, 0.32230897]],

       [[0.91008964, 0.07364013],
        [0.71214375, 0.90095865],
        [0.46316516, 0.24988243]]])

# Basic math operations

In [14]:
np.add(a1,a2)

array([[[1.06092063, 0.56197581],
        [1.26834583, 1.11868448],
        [1.26651832, 1.31525368]],

       [[1.15951791, 0.3735556 ],
        [0.78428231, 1.23035105],
        [1.45112431, 0.46772621]]])

In [15]:
np.subtract(a1,a2)

array([[[-0.20959966, -0.08837415],
        [ 0.46024428,  0.12997026],
        [ 0.57272615,  0.67063575]],

       [[-0.66066137,  0.22627533],
        [-0.64000519, -0.57156626],
        [ 0.52479399, -0.03203866]]])

In [50]:
np.divide(a1,a2)

array([[[0.73970065, 3.41448999],
        [1.0790072 , 0.99478818],
        [0.09449237, 0.84295711]],

       [[0.35342661, 0.33831233],
        [0.06498012, 0.36836924],
        [0.47768636, 1.17008678]]])

In [51]:
np.multiply(a1,a2)

array([[[4.96718896e-01, 2.63587017e-01],
        [2.79994680e-01, 4.61954848e-01],
        [2.77976626e-04, 1.54841815e-01]],

       [[4.65540386e-02, 9.48971127e-02],
        [3.59427388e-02, 5.03654569e-02],
        [5.10216562e-02, 4.64332130e-01]]])

##### Statistical operations 

In [54]:
sqrt = np.sqrt(25)
abs = np.abs(-2)
power = np.power(2,8)
log = np.log(25)
mins = np.min(a1)
maxs = np.max(a2)

In [55]:
sqrt

np.float64(5.0)

In [58]:
abs

np.int64(2)

In [59]:
power

np.int64(256)

In [60]:
log

np.float64(3.2188758248682006)

In [61]:
mins

np.float64(0.005125102027825346)

In [62]:
maxs

np.float64(0.819459209163078)

### Update

In [16]:
arr3


array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [64]:
arr3[0,0,2] = 500

In [66]:
arr3

array([[[  1,   2, 500],
        [  4,   5,   6]],

       [[  1,   2,   3],
        [  4,   5,   6]]])

In [70]:
arr3.sort()
arr3
arr3.shape

(2, 2, 3)

In [76]:
# reshape
arr_reshape = arr3.reshape((3,2,2))
arr_reshape

array([[[  1,   2],
        [500,   4]],

       [[  5,   6],
        [  1,   2]],

       [[  3,   4],
        [  5,   6]]])

## Appending and inserting values

In [77]:
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [17]:
new_arr = np.ones((3,2,3))
new_arr

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [18]:
appd = np.append(zeros,new_arr,axis=1)
appd

array([[[0., 0., 0.],
        [0., 0., 0.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [86]:
# insert

In [88]:
zeros


array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [91]:
new_arr

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [19]:
insrt_arr = np.insert(zeros,1,new_arr,axis=0)
insrt_arr

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [20]:
# Delete
arr4 = np.random.rand(3,2,3)
arr4

array([[[0.25999091, 0.7928711 , 0.8591937 ],
        [0.08259695, 0.17941917, 0.82923647]],

       [[0.57281666, 0.05395881, 0.28156641],
        [0.6144466 , 0.99559693, 0.59230011]],

       [[0.65500427, 0.31601223, 0.40495374],
        [0.96173075, 0.13755137, 0.28663926]]])

In [21]:
# deleting array 
arr5 = np.delete(arr4,0,axis=1)


In [23]:
np.save("new_array",arr5)